### PR TITLE
Project tokens

### PR DESCRIPTION
**Pull request by GarboMuffin**
Still don't know when they're doing this so I'm just getting ready while I have time

### CODE REVIEW

**Comment by GarboMuffin** [comment]
This PR being merged doesn't mean that anything has changed about unshared projects yet. It's just some internal development happenings so that the project is ready for the future.

**Comment by joshpinto6** [comment]
Hey @Garbomuffin, do you know if the unshared project changes in Scratch (not allowing unshared projects to be accessed without a token?) will affect setting unshared projects to the Featured Project slot on a user's profile? 

I'm just curious, but I was wondering what extent of unshared projects' data will likely be accessible after this update.

**Comment by GarboMuffin** [comment]
There isn't any reason to believe a featured unshared project would behave any differently than any other unshared projcet

**Comment by joshpinto6** [comment]
Okay. I was just wondering if non-authenticated users would still be able to access the thumbnail through the API. Thanks!

**Comment by GarboMuffin** [comment]
I thought you were talking about loading projects, not about just setting them as the featured project. Thumbnails do not appear to be affected by project tokens (which is itself a less severe version of the loading unshared projects bug that should've been fixed a long time ago). I have no way of predicting whether the Scratch API will let you set your featured project to be an unshared one in the future.

**Comment by joshpinto6** [comment]
> I have no way of predicting whether the Scratch API will let you set your featured project to be an unshared one in the future.
OKay, Thanks!

**Pull request merged**
