### PR TITLE
Full CSS makeover

### PR DESCRIPTION
**Pull request by micahlt**
This PR includes a full CSS makeover.  About half of it is stuff I've written myself and the other half is powered by [Materialize](https://materializecss.com/).  You can view my demo of it [here](https://micahlindley.com/p3).  The full list of improvements: 

- A `README.md` file
- Split CSS and HTML into separate files
- More responsive units (`rem` and `em` instead of `px`)
- Include Materialize CSS
- Include Material Icons
- Hide browser default file selectors
- Replace browser default alerts with Materialize alerts
- Set Roboto as the font

If this PR is approved, I'd appreciate if you'd label this issue as `hacktoberfest-accepted`, as I'm participating in the challenge 😄

### CODE REVIEW

**Comment by GarboMuffin** [comment]
I added the label so you can get your free shirt.

I'm not going to merge this for now. There's still some basic functionality I need to get working first.

**Comment by micahlt** [comment]
Sounds good!  And just so you know, I'm not just making this PR for the shirt.  I'm interested in making this project as useful as possible 😁

**Comment by GarboMuffin** [comment]
I incorporated the parts of this PR I like the most into master: https://garbomuffin.github.io/p3/

I'm not a big fan of material design and I don't want to add external fonts/scripts, everything should be in this repository.

Styles still aren't final of course. The inputs are still quite ugly. I also want to add descriptions to most of them, it's not clear where those will go right now.

**Comment by micahlt** [comment]
Looks nice!  Yeah, I know some people don't like MD, but at least I gave it a try. 😶 I'll keep that in mind for future contributions.  Sounds good - if you'd like I can work on custom input styles when I get the time.  Perhaps descriptions could be hover text or even custom tooltips.

**Comment by GarboMuffin** [comment]
I guess this is a bit old now

If you're interested, next hactoberfest, I'll actually make an effort to get something merged, probably

**Comment by micahlt** [comment]
@GarboMuffin If you are still looking for something like this, I could care less if it's Hacktoberfest or not.  I just want to see this project succeed 😄

**Comment by GarboMuffin** [comment]
If you're looking for something to work on, how about https://github.com/TurboWarp/packager/issues/23

Or, since a rewrite and redesign launched yesterday on https://packager.turbowarp.org/, I'd love to hear some ideas to make the site look nicer. (web design is not a strong point for me)

**Pull request closed without merging**
